### PR TITLE
feat: [TASK-6] add sqs, sns, catalogProducts lambda

### PR DESCRIPTION
**Pull request by IgorByl**
Task 6 (SQS & SNS, Async Microservices Communication)

1 - File serverless.yml contains configuration for catalogBatchProcess function
2 - File serverless.yml contains policies to allow lambda catalogBatchProcess function to interact with SNS and SQS
3 - File serverless.yml contains configuration for SQS catalogItemsQueue
4 - File serverless.yml contains configuration for SNS Topic createProductTopic and email subscription

Additional:
0 (All languages) - catalogBatchProcess lambda is covered by unit tests
1 (All languages) - set a Filter Policy for SNS createProductTopic in serverless.yml and create an additional email subscription to distribute messages to different emails depending on the filter for any product attribute

Total: 5

### CODE REVIEW

**Comment by IgorByl** [comment]
image

**Comment by IgorByl** [comment]
image

**Comment by IgorByl** [comment]
image

**Comment by milanaadams** [comment]
Could you please provide relevant frontend app link?

**Comment by IgorByl** [comment]
> Could you please provide relevant frontend app link?

https://d3v7dkxyx8gkab.cloudfront.net

**Pull request merged**
